#!/bin/bash
# https://github.com/linzor/u 
# Arch Linux update script v1.1

# Options:

# Define an aur helper
aurh="paru"

# Define if you want notifications (doesnt include errors)
notifyonstepcomplete="1" 

# Define if you want to build an init image
# 0 = dont build an image
# 1 = automatically build an image
# 2 = ask everytime
initimage="2"

# Define a command for building an image
cmdgenimg="sudo mkinitcpio -p linux"

# Enable/Disable ntp system time update 
# Depends on ntp package
UpdateNTP="1"

# Define an ntp update time server (Default: time.nist.gov)
NTPserver="time.nist.gov"

# Define if you want to look for a new ntp server (in case your default doesn't work)
NTPFindNewServer="1"

# Define prefered ntp servers region (in case your default doesn't work)
NTPregion="europe"

# CONFIG_END
# 
#

function Uconfig(){
which u 2>/dev/null >/dev/null && ufip="1" || ufip="0" 
[[ $ufip = "0" ]] && printf "\e[1;32m%-6s\e[m\n" " script is not in your path"
[[ $ufip = "1" ]] && $EDITOR $(which u)
exit 1
}

function helpmenu(){
echo "u - Arch Linux update shell script"
echo "Script can be configured by editing the source."
echo "If you have added this script to your PATH use -c"
echo "Options:"
echo "-c	opens the script in $EDITOR"
echo "-h	this message"
echo "-s	forces the init image generation, adds '--noconfirm' and shuts down the system (unless update errors out)"
echo "-r	forces the init image generation, adds '--noconfirm' and reboots the system (unless update errors out)"
echo "-f	direct call function from script (example: ./u.sh -f ntpgetserverlist)"
echo "
Current settings:"
echo "aurh=$aurh"
echo "notifyonstepcomplete=$notifyonstepcomplete"
echo "initimage=$initimage"
echo "cmdgenimg=$cmdgenimg"
echo "UpdateNTP=$UpdateNTP"
echo "NTPserver=$NTPserver"
echo "NTPregion=$NTPregion"
echo "NTPFindNewServer=$NTPFindNewServer"
exit 1
}

function directcallfunc(){
$*
}

function noroot(){
errnr="
need sudo permissions
"
notify-send -a "u.sh" "$errnr"
printf "\e[1;31m%-6s\e[m\n" "$errnr"
}

function yroot(){
yrt="sudo permission granted"
printf '\e[1;32m%-6s\e[m\n' "$yrt"
Umain
}

function ntpcheckserver(){
if [[ "$(ntpgetserverstate $NTPserver)" = "0" ]];then
	if [[ "$var_ntpcheck_count" = "7" ]];then
		printf "\e[1;33m%-6s\e[m\n" "NTP Server ($NTPserver) is not responding"
		sleep 1
		if [[ "$NTPFindNewServer" = "1" ]];then
		echo "Looking for a different NTP Server . . ."
		ntpswitchserver
		else
		echo "Setting NTPFindNewServer is set to $NTPFindNewServer"
		Stop NTP Update	
		fi
	else
	var_ntpcheck_count="$(expr $var_ntpcheck_count + 1)"
	ntpcheckserver
	fi
fi
}

ntpswitchserver(){
NTPserver="$(echo -n "$(ntpgetserverlist)" | sed -n $(shuf -i 1-$(ntpgetserverlist | wc -l) -n 1)p)"
if [[ "$(ntpgetserverstate $NTPserver)" = "1" ]];then
printf "\e[1;32m%-6s\e[m\n" "New NTP Server: $NTPserver"
else
nss_count="$(expr $nss_count + 1)"
echo "Checking server: $NTPserver ($nss_count)"
sleep 1
if [[ "$nss_count" = "10" ]];then
Stop ntpswitchserver
else
ntpswitchserver
fi
fi
}

function ntptimeupdate(){
if [[ $UpdateNTP = "1" ]];then
ntpcheckserver
echo "Current OS time: $(date)"
printf "\e[1;32m%-6s\e[m\n" "NTP-server: $NTPserver"
sudo ntpdate -s $NTPserver && stepcomplete NTP Update || Stop ntp
echo "Hardware clock: $(sudo hwclock -u)"
echo "Updated OS time: $(date)"
else
printf "\e[1;32m%-6s\e[m\n" "Skiping over ntp time update ..."
fi
}

function ntpgetserverstate(){
ping -c 1 $1 >/dev/null 2>/dev/null && echo '1' || echo '0'
}

function ntpgetserverlist(){
var_ntpserverlistloc='/tmp/u.cache.ntp.server.list'
cat $var_ntpserverlistloc 2>/dev/null | grep '.ntp.org' >/dev/null 2>/dev/null && vnsll='1'
if [[ "$vnsll" = '1' ]];then
cat $var_ntpserverlistloc
else
curl https://www.ntppool.org/zone/$NTPregion -s | grep '.org' | grep '.ntp.' | grep '<a href="/zone/' | cut -d ';' -f2 | cut -d '(' -f1 | sed -e 's/ //g' > $var_ntpserverlistloc 
var_ngsl_count="$(expr $var_ngsl_count + 1)"
if [[ "$var_ngsl_count" = "5" ]];then
stp="Couldn't get the NTP server list"
notify-send -a "u.sh" "$stp" & disown
printf "\e[1;33m%-6s\e[m\n" "$stp" > $var_main_tty 2>/dev/null
kill $$ 2>/dev/null
else
ntpgetserverlist
fi
fi
}

function mlocale(){
printf "\e[1;34m%-6s\e[m\n" "Updating mlocale database..."
sudo updatedb && stepcomplete mlocale || Stop mlocale
}

function checkmlocale(){
#checks for the mlocale package utils
which locate || nml=1
which updatedb || nml=1
if [[ $nml = "1" ]];then
printf "\e[1;31m%-6s\e[m\n" "mlocale not found, skiping..." 
else
mlocale
fi
}

function Stop(){
stp="$* errored out. Stoping update ..."
notify-send -a "u.sh" "$stp" & disown
printf "\e[1;33m%-6s\e[m\n" "$stp"
kill $$ &
}

function stepcomplete(){
sct="$* process complete, moving on ..."
if [[ $notifyonstepcomplete = 1 ]];then
notify-send -a "u.sh" "$sct"
fi
printf "\e[1;34m%-6s\e[m\n" "$sct"
}

function GenImage(){
genit="Starting Init Image Generation ..."
printf "\e[1;34m%-6s\e[m\n" "$genit"
notify-send -a "u.sh" "$genit"
sh -c "$cmdgenimg" && stepcomplete init image generation || Stop Image Generation
}

function GenImageAsk(){
skpimg="Skiping over init image generation"
if [[ $initimage = "1" ]];then
GenImage
fi
if [[ $initimage = "2" ]];then
read -p "Do you want to generate an init image? [y/n]: " gimga
if [[ $gimga = "y" ]];then
GenImage
else
printf "\e[1;34m%-6s\e[m\n" "$skpimg"
fi
fi
if [[ $initimage = "0" ]];then
printf "\e[1;34m%-6s\e[m\n" "$skpimg"
fi
}

function Umain(){
rut="Running Update ..."
printf "\e[1;34m%-6s\e[m\n" "$rut"
notify-send -a "u.sh" "$rut"
ntptimeupdate
sudo pacman -Syu $noconfirm && stepcomplete Pacman || Stop Pacman
$aurh -Syu $noconfirm && stepcomplete $aurh || Stop $aurh
checkmlocale
stepcomplete Update
GenImageAsk
sh -c "$SRFv"
echo " Done."
}

function SF(){
initimage="1"
SFT="System is set to shutdown 10 seconds after update.

Image Generation is Forced.
"
notify-send -a "u.sh" "$SFT"
printf "\e[1;31m%-6s\e[m\n" "$SFT"
SRFv='notify-send -a "u.sh" "Shutdown in 10 seconds ..." ; echo "Shutdown in 10 seconds ..." && sleep 9 && notify-send -a "u.sh" "bye bye <3" && sleep 1 && systemctl poweroff'
noconfirm="--noconfirm"
}

function SR(){
initimage="1"
SRT="System is set to reboot 10 seconds after update.

Image Generation is Forced.
"
notify-send -a "u.sh" "$SRT"
printf "\e[1;31m%-6s\e[m\n" "$SRT"
SRFv='notify-send -a "u.sh" "Reboot in 10 seconds ..." ; echo "Reboot in 10 seconds ..." && sleep 10 && systemctl reboot'
noconfirm="--noconfirm"
}

while getopts 'chsrf' FLAGS >/dev/null ; do
case "$FLAGS" in
	c)
		Uconfig
		;;
	h)
		helpmenu
		;;
	s)
		SF
		;;
	r)
		SR
		;;
	f)
		directcallfunc $2 $3 $4 $5 $6 $7 $8 $9
		exit 1
		Stop callfunc
		;;
	?)
	echo " "
	helpmenu
	;;
esac
done
var_main_tty="$(tty)"
echo "$var_main_tty" > /dev/null
sudo printf "" && yroot || noroot
